#!/usr/bin/env bash

set -e

LD=arm-none-eabi-ld
OBJCOPY=arm-none-eabi-objcopy

OUTPUT="$1"
shift 1
rm -f "${OUTPUT}"

POS=0

while [ ! -z "$1" ]; do
  NAME="$(basename "$1" .elf)"
  sed "s/\+ (0)/+ (${POS})/" apps/external.ld > temp.ld
  "${LD}" "$1" -o "${NAME}_linked.elf" -Ttemp.ld
  "${OBJCOPY}" -O binary "${NAME}_linked.elf" "${NAME}"
  tar -rf "${OUTPUT}" "${NAME}"
  POS=$(( ${POS} + (($(stat --printf="%s" "${NAME}") + 1023)/512)*512 ))
  rm -f temp.ld "${NAME}" "${NAME}_linked.elf"
  shift 1
done
