#! /bin/sh
export CC=/usr/bin/gcc
export CXX=/usr/bin/g++
export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/
#cd ~/tmp
#rm -rf giac-0.6.1
#tar xvfz ~/giac/giac-1.1.4.tar.gz
#cd debian
#cp -f rules.pari rules
#cd ..
#export CXXFLAGS='-g -L/usr/local/lib'
#export CXXFLAGS='-DSMARTPTR64 -D_I386_ -O2'
#mv debian debiannew
#mv debianold debian
#mv debiannew debianold
dpkg-buildpackage -rfakeroot
#mv debian debiannew
#mv debianold debian
#mv debiannew debianold
#dpkg-buildpackage -us -uc -rfakeroot
