#!/usr/bin/env bash

set -e

function build {
  (
    cd src/gmp-6.2.0
    ./configure --host=arm-none-eabi --disable-assembly CFLAGS="$2"
    make -j $(nproc)
    cp .libs/libgmp.a ../lib/
    cp gmp.h ../include/gmp.h
    make distclean
  )

  (
    cd src/mpfr-4.0.2
    ./configure --with-gmp=../ --host=arm-none-eabi --disable-shared CFLAGS="$2"
    make -j $(nproc)
    cp src/.libs/libmpfr.a ../lib/
    cp src/mpfr.h ../include/mpfr.h
    make distclean
  )

  (
    cd src/mpfi-1.5.4
    
    # Quick and dirty hack for github pages to work
    # Setup symlinks manually
    mkdir build-aux
    mkdir m4
    
    ln -s /usr/share/libtool/build-aux/ltmain.sh    build-aux/ltmain.sh
    ln -s /usr/share/automake-1.16/missing          build-aux/missing
    ln -s /usr/share/automake-1.16/config.sub       build-aux/config.sub
    ln -s /usr/share/automake-1.16/compile          build-aux/compile
    ln -s /usr/share/automake-1.16/config.guess     build-aux/config.guess
    ln -s /usr/share/automake-1.16/test-driver      build-aux/test-driver
    ln -s /usr/share/automake-1.16/install-sh       build-aux/install-sh
    ln -s /usr/share/automake-1.16/ar-lib           build-aux/ar-lib
    ln -s /usr/share/automake-1.16/depcomp          build-aux/depcomp
    ln -s /usr/share/aclocal/ltoptions.m4           m4/ltoptions.m4
    ln -s /usr/share/aclocal/ltsugar.m4             m4/ltsugar.m4
    ln -s /usr/share/aclocal/libtool.m4             m4/libtool.m4
    ln -s /usr/share/aclocal/lt~obsolete.m4         m4/lt~obsolete.m4
    ln -s /usr/share/aclocal/ltversion.m4           m4/ltversion.m4
    
    
    ./configure --with-mpfr=$(pwd)/../ --with-gmp=$(pwd)/../ --host=arm-none-eabi CFLAGS="$2"
    make -j $(nproc)
    cp src/.libs/libmpfi.a ../lib/
    cp src/mpfi.h ../include/mpfi.h
    make distclean
    
    rm -r build-aux
    rm -r m4
  )
}

# build n0100 "-Os -fdata-sections -ffunction-sections -DNDEBUG -mthumb -march=armv7e-m -mfloat-abi=hard -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -fno-strict-aliasing --specs=nosys.specs"
build n0110 "-Os -fdata-sections -ffunction-sections -DNDEBUG -mthumb -march=armv7e-m -mfloat-abi=hard -mcpu=cortex-m7 -mfpu=fpv5-sp-d16 -fno-strict-aliasing --specs=nosys.specs"
