#!/usr/bin/env bash

set -e

function build {
  (
    cd src/giac-1.6.0/src
    rm -f *.o *.a
    make -f Makefile.numworks.$1 -j $(nproc)
    cp libgiac.a ../../lib/
    rm -f *.o *.a
  )
}

#build n0100
build n0110
#build simulator
